local PlaceId = game.PlaceId

if game.PlaceId == 129009554587176 or game.PlaceId == 76558904092080 then
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Yenixs/Blockspin-Premium/refs/heads/main/The-Forge.luau'))();
elseif game.PlaceId == 95898900045000 or game.PlaceId == 97556409405464 or game.PlaceId == 102036043572089 or game.PlaceId == 104715542330896 or game.PlaceId == 113269916962108 or game.PlaceId == 132247642420063 then 
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Yenixs/Blockspin-Premium/refs/heads/main/Pvp-Script.luau'))();
 end
